#!/usr/bin/env python
# -*- coding: utf-8 -*-
# This script is part of the ToolInfoWarehouse pilot project
# it converts the json generated by other tools (import from
# Gensoft@Pasteur, Galaxy@Pasteur, etc.
import pystache
import json
import argparse

def generate_xmls(json_filenames):
    xml_template_str = unicode(open('tool-template.xml').read())
    xml_template = pystache.parse(xml_template_str)
    for tool_path in json_filenames:
        desc = json.load(open(tool_path))
        desc['collectionName'] = desc['collectionName'].capitalize()
        print pystache.render(xml_template, desc)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
                 description='Convert TIW JSON to XML files')
    parser.add_argument('filenames', help=
                        "files you want to convert", nargs='+')
    args = parser.parse_args()
    filenames = args.filenames
    generate_xmls(filenames)
